### ISSUE TITLE
pls add ´webext-keepassxc-browser' for debian OS's...

### ISSUE THREAD

**Issue by flobee** [keepassxreboot/keepassxc-org#111]
... for debian stable users for firefox so that people do not download the extension (latest) from mozilla which will not work currently(1.8.6) with the debian package for keepassxc (2.7.2 which needs, works best with keepassxc-browser plugin 1.7.4)

https://keepassxc.org/download/#
```
[Ubuntu / Debian (distribution package)](https://packages.ubuntu.com/source/keepassxc)
sudo apt install keepassxc
+ sudo apt install keepassxc webext-keepassxc-browser # including firefox plugin
```

**Comment by droidmonkey** [comment]
There is no incompatibility between 1.8.6 web extension and keepassxc 2.7.2.

**Comment by flobee** [comment]
Hi, thx for reply.  FF is not that old 91.13.0: https://www.mozilla.org/en-US/firefox/91.13.0/releasenotes/

and 1.8.6 does not work. Manually tested, all >1.7.* work,

**Comment by droidmonkey** [comment]
The age of the browser is irrelevant. It is no longer receiving security patches which makes it unsupported and very high risk.

**Comment by phoerious** [comment]
I think the list of different ways to install the same thing on Linux is long enough as is. The whole list is already more of a fan service than anything, so I'm not going to add any other idiosyncratic options to it.
