### ISSUE TITLE
download page give me the wrong apple version

### ISSUE THREAD

**Issue by remijouannet** [keepassxreboot/keepassxc-org#114]
Hello,

i use firefox on an old Macbook (i'm stuck on catalina), the webpage https://keepassxc.org/download/# serve me the silicon binary by default, the download link generate by the update checker also download the wrong binary

**Comment by phoerious** [comment]
Click on "See more options" to download the correct version for your device. At the moment, there is no way we can detect what version you need unless you use Chrome.
