### ISSUE TITLE
Add browser extension to the download page

### ISSUE THREAD

**Issue by Shrinks99** [keepassxreboot/keepassxc-org#123]
Today while setting up a family member with the KeepassXC browser extension for Firefox I went over to the site only to find it missing!  To help new users get up and running quicker it would be great to have authoritative links to the browser extension listed on the site.

I'd be willing to help add this!  I'm already half way through implementing it... Though I figure I should open an issue here first to coordinate rather than submit an unsolicited PR... Perhaps there's a reason it's currently omitted?

### Success Criteria

- Link to the [Microsoft Edge Extension](https://microsoftedge.microsoft.com/addons/detail/keepassxcbrowser/pdffhmdngciaglkoonimfcmckehcpafo), [Chrome Extension](https://chromewebstore.google.com/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk), and [Firefox Add-On](https://addons.mozilla.org/en-CA/firefox/addon/keepassxc-browser/) with a tab on the download page
- Note that this is a companion to the app and not a standalone password manager to ensure users download the correct applications.

**Comment by droidmonkey** [comment]
We show this when you download the application from the website. A popup or similar asks you to install the extension. It is also listed (and linked) in our getting started and user guides. 

Happy to add another set of links if it makes it even more clear.

**Comment by Shrinks99** [comment]
Ah that explains it!  Good UX for new users, but doesn't cover the folks that _don't_ install it right away.

I'd keep that but add the extension as a separate tab as well?  Currently adding the extension badges but might switch to the existing browsers and install buttons... They're probably nicer.

<img width="957" alt="Screenshot 2023-10-26 at 12 36 59 AM" src="https://github.com/keepassxreboot/keepassxc-org/assets/5672810/39239efc-c601-474a-93b3-4f32e0d0355c">

**Comment by phoerious** [comment]
Sure.
