### ISSUE TITLE
Add note to FAQ about Wayland and Auto-Type

### ISSUE THREAD

**Issue by JohnVeness** [keepassxreboot/keepassxc-org#125]
The answer to "[Is Auto-Type supported on macOS, Windows and Linux?](https://keepassxc.org/docs/#faq-autotype)" should maybe mention Auto-Type doesn't work with Wayland?

**Comment by droidmonkey** [comment]
Sure, it's in the docs as well: https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type

**Comment by JohnVeness** [comment]
Thanks. Hmm, I still can't get Auto-Type to work, even with "-platform xcb", but this probably isn't the right place to discuss that. I just thought it was worth mentioning in the FAQ, especially as currently it reads like there is no problem.

**Comment by droidmonkey** [comment]
In order to use Auto-Type, every application needs to run on X11. KeePassXC and the app you want to type into.
