### ISSUE TITLE
could you add Bitcoin Cash Address back to donations?

### ISSUE THREAD

**Issue by emergent-reasons** [keepassxreboot/keepassxc-org#127]
It was there for several years but missing since it seems like [this commit](https://github.com/keepassxreboot/keepassxc-org/commit/f8616b5693b57b9d75511b3bb261a20f2e2f4033).

I was going to make a PR with the old address, but adding addresses is a touchy thing obviously so I'm just asking.

Thank you for the work you do.

**Comment by droidmonkey** [comment]
I frankly don't want crypto. Thank you, but we will likely remove everything but BTC.
