### ISSUE TITLE
Update year in footer

### ISSUE THREAD

**Issue by hugo-sid** [keepassxreboot/keepassxc-org#130]
## What's the issue?

It's 2024 🎉, but the the website displays 2023 in the footer.

![image](https://github.com/keepassxreboot/keepassxc-org/assets/122173059/1fc4dc60-d83c-4297-89b4-658660ca0cf4)

## Fix

I believe, triggering a new deploy on Cloudflare pages will fix this issue; unless Cloudflare's CI runners are in a location where it's still 2023. 😃 

## Reference(s)

https://github.com/keepassxreboot/keepassxc-org/blob/c0a05c2ad81b0f05756ad79666c7755c1c524e44/layouts/partials/footer.html#L11-L14

BTW, thanks for maintaining KeePassXC.

**Comment by droidmonkey** [comment]
It'll get taken care of on next website change.
