### ISSUE TITLE
KeePassXC public key - expiration dates wrong

### ISSUE THREAD

**Issue by arcticpinecone** [keepassxreboot/keepassxc-org#133]
## Overview
When trying to verify downloaded files using gpg on Windows, there is a discrepancy on the subkey expirations. 
Listed on the page is '20**24**-12-04'
When using the imported key from keys.openpgp.org, the valid to dates are '20**28**-12-08'.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Visit: https://keepassxc.org/verifying-signatures
2. Import key per instructions, or using 'release@keepassxc.org' in say, Kleopatra.
3. Using the suggested command: `gpg --verify KeePassXC-*.sig` resulted in a BAD signature. 
_Specifying_ the specific signature files 2.7.8, (both zip and msi) will then say good, but ofc is untrusted. 

The biggest problem here is that the dates you list as master and for us to be able to verify as trusted per your website, are not up to date. For clarity and less confusion, please update the expiration dates on the website to reflect the updated expirations.

Operating System: Windows 11

**Comment by phoerious** [comment]
There's a reason why we put this big warning at the top:
![Screenshot from 2024-05-31 17-38-03](https://github.com/keepassxreboot/keepassxc-org/assets/911270/32e95fb7-673c-4dbc-82f1-812f0b52e159)
