### ISSUE TITLE
FAQ: Auto-Type works on wayland

### ISSUE THREAD

**Issue by Application-maker** [keepassxreboot/keepassxc-org#138]
On the [589th line](https://github.com/keepassxreboot/keepassxc-org/blob/main/content/docs/index.html#L589) of FAQ, it says "on Linux it only works in an X11 session, not Wayland." about Auto-Type.
I don't know how it works for others, but for me, Auto-Type does work on Wayland, almost perfectly

**Comment by phoerious** [comment]
It doesn't. If Auto-Type is enabled for you, you are running KeePassXC in XWayland and you will only be able to auto-type into other XWayland windows.
